### ISSUE TITLE
Methods for writing data not implemented?

### ISSUE THREAD

**Issue by zachmullen** [spotify/snakebite#139] opened 2015-03-04 19:34 UTC
It appears that the client doesn't have methods like `put` or `appendToFile`, and the documentation doesn't make it clear whether this is possible. Is there a way to write files to HDFS using snakebite? If not, are there plan to implement that?

**Comment by wouterdebie** [comment] 2015-03-04 19:50
Duplicate of #37

**Closed by wouterdebie** 2015-03-04 19:50 UTC
