### ISSUE TITLE
No copyFromLocal function in CLI client command line

### ISSUE THREAD

**Issue by qianglchina** [spotify/snakebite#183] opened 2016-01-06 09:04 UTC
Hi,
I have checked the usage of command line. There is only "copyToLocal"  and I can't  find "copyFromLocal". 

how should i do if i want to put local file to hdfs by this client ?

**Comment by crorella** [comment] 2016-02-17 22:51
They disabled that option in 2.2, not sure why.

**Comment by wouterdebie** [comment] 2016-02-25 16:42
The option was there, but it was never implemented and was confusing.

Duplicate of #37

**Closed** 2016-02-25 16:42 UTC
Labels: duplicate
