### ISSUE TITLE
can not put file to hdfs

### ISSUE THREAD

**Issue by francisar** [spotify/snakebite#211] opened 2016-07-26 05:51 UTC
this client doesn't support put file to hdfs

**Comment by guhehehe** [comment] 2016-07-27 00:24
there's a [thread for this feature](https://github.com/spotify/snakebite/issues/37) long time ago, but somehow it's never implemented.

**Comment by wouterdebie** [comment] 2016-07-27 00:31
Yep, duplicate of #37

**Closed by wouterdebie** 2016-07-27 00:31 UTC

**Comment by francisar** [comment] 2016-07-27 05:36
wait for it

**Comment by lixiang2017** [comment] 2019-07-17 03:25
wait for it
